### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Joabutt** [xXDeathAbyssXx/wwebjs-sender#12]
How do i send a message collector in dms?

**Comment by xXDeathAbyssXx** [comment]
Hello, I apologize for the delayed response. I truly don't recommend using my package at the moment because it relies on a very outdated version of whatsapp-web.js. In addition to the designs and collectors, one of the primary features of this package was the buttons, and the developers of whatsapp-web.js are no longer maintaining support for buttons and lists. I'm considering waiting a bit longer to see if they reintroduce these features or possibly migrating my package to another WhatsApp module.
