### ISSUE TITLE
Button with Media

### ISSUE THREAD

**Issue by ShanthiniMM** [xXDeathAbyssXx/wwebjs-sender#7]
Hi, Is there any way to send the button with the media file? Kindly let me know.

**Comment by xXDeathAbyssXx** [comment]
Hi! Sorry for not reading your message, I had some problems with my computer and the truth is that I have not updated the package surely there may be errors I will have to change it to deprecated since I do not have time to continue maintaining this, and I do not think you can do that until what is according to the documentation these are the "body" parameters, buttons, title, footer. " You should still go to ask any questions about whatsapp-web to their official server.

**Comment by xXDeathAbyssXx** [comment]
But I will try to keep the project and add new functions, if you have any questions about whatsapp-web.js functions you should go to the discord server.
